{
 "title": "Google's Golden Rules",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "addr", "query": "request_seconds_count:irate" },
   { "name": "type", "query": "request_seconds_count:irate" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Error rate",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(request_seconds_count:irate{status!~\"2..\"}) by (addr)\n  /\n  sum(request_seconds_count:irate) by (addr)\n)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Latency",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(request_seconds_sum:irate) by (addr)\n  /\n  sum(request_seconds_count:irate) by (addr)\n)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Top 10 Throughput",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,\n  sum(request_seconds_count:irate{status!~\"2..\"}) by (addr)\n)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "title": "$addr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "repeat": "addr" },
  {
   "title": "Throughput and Latency",
   "type": "graph",
   "description": "Throughput and Latency of $addr",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Throughput "
    },
    {
     "expr": "sum(request_seconds_sum:irate{addr=\"$addr\", type=\"$type\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\", type=\"$type\"}) by (addr, prsn, type)",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Throughput and Error rate",
   "type": "graph",
   "description": "Throughput and Error rate of $addr",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\"}) by (addr)",
     "legendFormat": "Throughput {{addr}}"
    },
    {
     "expr": "sum(request_seconds_count:irate{addr=\"$addr\", status!~\"2..\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\"}) by (addr, prsn, type)",
     "legendFormat": "Error rate {{addr}}"
    }
   ]
  },
  {
   "title": "Latency and Error rate",
   "type": "graph",
   "description": "Latency and Error rate of $addr",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(request_seconds_sum:irate{addr=\"$addr\"}) by (addr, prsn)\n/\nsum(request_seconds_count:irate{addr=\"$addr\"}) by (addr, prsn)",
     "legendFormat": "Latency {{addr}} {{prsn}}"
    },
    {
     "expr": "sum(request_seconds_sum:irate{addr=\"$addr\",status!~\"2..\"}) by (addr, prsn, type)\n/\nsum(request_seconds_count:irate{addr=\"$addr\"}) by (addr, prsn, type)",
     "legendFormat": "Error rate  {{addr}}"
    }
   ]
  }
 ]
}